# Makefile for Win32

TOP = ..\..

!include "$(TOP)/win32.mak"

SRCS = gizmo.c glutmui.c displaylist.c uicolor.c miscui.c mui.c vslider.c textlist.c button.c pulldown.c hslider.c
OBJS = $(SRCS:.c=.obj)

NO_EXE=1

all	: mui.lib install

!include "$(TOP)/glutwin32.mak"

mui.lib	: $(OBJS)
	lib -out:mui.lib $(OBJS)

install:mui.lib
	-copy mui.lib $(LIBINSTALL)
	